config/routes.rb
Rails.application.routes.draw do
  get 'home/home'

  get 'report/report'

  get 'invoice/invoice'

  resources :office_days

  resources :appointments

  resources :patients

  resources :statuses

  resources :time_slots

  resources :diagnostics

  resources :physicians

  resources :insurances

   root 'home#home'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :physician
  belongs_to :diagnostic
  belongs_to :status
  belongs_to :time_slot
  belongs_to :office_day
  validates_presence_of :fee



end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base
  has_many :appointments
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
end

app/models/office_day.rb
class OfficeDay < ActiveRecord::Base
  has_many :appointments
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, :through => :appointments
  belongs_to :insurance
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :patients, :through => :appointments

  end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :appointments
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  has_many :appointments
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/office_days_controller.rb
class OfficeDaysController < ApplicationController
  before_action :set_office_day, only: [:show, :edit, :update, :destroy]

  # GET /office_days
  # GET /office_days.json
  def index
    @office_days = OfficeDay.all
  end

  # GET /office_days/1
  # GET /office_days/1.json
  def show
  end

  # GET /office_days/new
  def new
    @office_day = OfficeDay.new
  end

  # GET /office_days/1/edit
  def edit
  end

  # POST /office_days
  # POST /office_days.json
  def create
    @office_day = OfficeDay.new(office_day_params)

    respond_to do |format|
      if @office_day.save
        format.html { redirect_to @office_day, notice: 'Office day was successfully created.' }
        format.json { render :show, status: :created, location: @office_day }
      else
        format.html { render :new }
        format.json { render json: @office_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /office_days/1
  # PATCH/PUT /office_days/1.json
  def update
    respond_to do |format|
      if @office_day.update(office_day_params)
        format.html { redirect_to @office_day, notice: 'Office day was successfully updated.' }
        format.json { render :show, status: :ok, location: @office_day }
      else
        format.html { render :edit }
        format.json { render json: @office_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /office_days/1
  # DELETE /office_days/1.json
  def destroy
    @office_day.destroy
    respond_to do |format|
      format.html { redirect_to office_days_url, notice: 'Office day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office_day
      @office_day = OfficeDay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_day_params
      params.require(:office_day).permit(:work_day)
    end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def report
      @appointments = Appointment.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/office_days_helper.rb
module OfficeDaysHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/office_days/_form.html.erb
<%= form_for @office_day, :html => { :class => "form-horizontal office_day" } do |f| %>

    <% if @office_day.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@office_day.errors.count, "error") %> prohibited this office_day from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @office_day.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :work_day, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :work_day, :class => 'form-control' %>
    </div>
    <%= error_span(@office_day[:work_day]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            office_days_path, :class => 'btn btn-default' %>

<% end %>

app/views/office_days/edit.html.erb
<%- model_class = OfficeDay -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/office_days/index.html.erb
<%- model_class = OfficeDay -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:work_day) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @office_days.each do |office_day| %>
      <tr>
        <td><%= link_to office_day.id, office_day_path(office_day) %></td>
        <td><%= office_day.work_day %></td>
        <td><%=l office_day.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_office_day_path(office_day), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      office_day_path(office_day),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_office_day_path,
            :class => 'btn btn-primary' %>

app/views/office_days/new.html.erb
<%- model_class = OfficeDay -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/office_days/show.html.erb
<%- model_class = OfficeDay -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:work_day) %>:</strong></dt>
  <dd><%= @office_day.work_day %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              office_days_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_office_day_path(@office_day), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              office_day_path(@office_day),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>