config/routes.rb
Rails.application.routes.draw do
  get 'home/home'

  get 'report/report'

  get 'invoice/invoice'

  resources :office_days

  resources :appointments

  resources :patients

  resources :statuses

  resources :time_slots

  resources :diagnostics

  resources :physicians

  resources :insurances

   root 'home#home'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :physician
  belongs_to :diagnostic
  belongs_to :status
  belongs_to :time_slot
  belongs_to :office_day
  validates_presence_of :fee



end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base
  has_many :appointments
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
end

app/models/office_day.rb
class OfficeDay < ActiveRecord::Base
  has_many :appointments
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, :through => :appointments
  belongs_to :insurance
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :patients, :through => :appointments

  end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :appointments
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  has_many :appointments
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:appointment_status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/office_days_helper.rb
module OfficeDaysHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/statuses/_form.html.erb
<%= form_for @status, :html => { :class => "form-horizontal status" } do |f| %>

    <% if @status.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @status.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :appointment_status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :appointment_status, :class => 'form-control' %>
    </div>
    <%= error_span(@status[:appointment_status]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            statuses_path, :class => 'btn btn-default' %>

<% end %>

app/views/statuses/edit.html.erb
<%- model_class = Status -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/statuses/index.html.erb
<%- model_class = Status -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:appointment_status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= link_to status.id, status_path(status) %></td>
        <td><%= status.appointment_status %></td>
        <td><%=l status.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_status_path(status), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      status_path(status),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_status_path,
            :class => 'btn btn-primary' %>

app/views/statuses/new.html.erb
<%- model_class = Status -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/statuses/show.html.erb
<%- model_class = Status -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:appointment_status) %>:</strong></dt>
  <dd><%= @status.appointment_status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              statuses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_status_path(@status), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              status_path(@status),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>