config/routes.rb
Rails.application.routes.draw do
  get 'home/home'

  get 'report/report'

  get 'invoice/invoice'

  resources :office_days

  resources :appointments

  resources :patients

  resources :statuses

  resources :time_slots

  resources :diagnostics

  resources :physicians

  resources :insurances

   root 'home#home'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :physician
  belongs_to :diagnostic
  belongs_to :status
  belongs_to :time_slot
  belongs_to :office_day
  validates_presence_of :fee



end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base
  has_many :appointments
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
end

app/models/office_day.rb
class OfficeDay < ActiveRecord::Base
  has_many :appointments
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, :through => :appointments
  belongs_to :insurance
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :patients, :through => :appointments

  end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :appointments
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  has_many :appointments
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :set_insurance, only: [:show, :edit, :update, :destroy]

  # GET /insurances
  # GET /insurances.json
  def index
    @insurances = Insurance.all
  end

  # GET /insurances/1
  # GET /insurances/1.json
  def show
  end

  # GET /insurances/new
  def new
    @insurance = Insurance.new
  end

  # GET /insurances/1/edit
  def edit
  end

  # POST /insurances
  # POST /insurances.json
  def create
    @insurance = Insurance.new(insurance_params)

    respond_to do |format|
      if @insurance.save
        format.html { redirect_to @insurance, notice: 'Insurance was successfully created.' }
        format.json { render :show, status: :created, location: @insurance }
      else
        format.html { render :new }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurances/1
  # PATCH/PUT /insurances/1.json
  def update
    respond_to do |format|
      if @insurance.update(insurance_params)
        format.html { redirect_to @insurance, notice: 'Insurance was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurance }
      else
        format.html { render :edit }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurances/1
  # DELETE /insurances/1.json
  def destroy
    @insurance.destroy
    respond_to do |format|
      format.html { redirect_to insurances_url, notice: 'Insurance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurance
      @insurance = Insurance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insurance_params
      params.require(:insurance).permit(:name, :toll_free)
    end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def report
      @appointments = Appointment.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/office_days_helper.rb
module OfficeDaysHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/insurances/_form.html.erb
<%= form_for @insurance, :html => { :class => "form-horizontal insurance" } do |f| %>

    <% if @insurance.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@insurance.errors.count, "error") %> prohibited this insurance from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @insurance.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@insurance[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :toll_free, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :toll_free, :class => 'form-control' %>
    </div>
    <%= error_span(@insurance[:toll_free]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            insurances_path, :class => 'btn btn-default' %>

<% end %>

app/views/insurances/edit.html.erb
<%- model_class = Insurance -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/insurances/index.html.erb
<%- model_class = Insurance -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:toll_free) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @insurances.each do |insurance| %>
      <tr>
        <td><%= link_to insurance.id, insurance_path(insurance) %></td>
        <td><%= insurance.name %></td>
        <td><%= insurance.toll_free %></td>
        <td><%=l insurance.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_insurance_path(insurance), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      insurance_path(insurance),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_insurance_path,
            :class => 'btn btn-primary' %>

app/views/insurances/new.html.erb
<%- model_class = Insurance -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/insurances/show.html.erb
<%- model_class = Insurance -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @insurance.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:toll_free) %>:</strong></dt>
  <dd><%= @insurance.toll_free %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              insurances_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_insurance_path(@insurance), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              insurance_path(@insurance),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>