config/routes.rb
Rails.application.routes.draw do
  get 'home/home'

  get 'report/report'

  get 'invoice/invoice'

  resources :office_days

  resources :appointments

  resources :patients

  resources :statuses

  resources :time_slots

  resources :diagnostics

  resources :physicians

  resources :insurances

   root 'home#home'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :physician
  belongs_to :diagnostic
  belongs_to :status
  belongs_to :time_slot
  belongs_to :office_day
  validates_presence_of :fee



end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base
  has_many :appointments
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
end

app/models/office_day.rb
class OfficeDay < ActiveRecord::Base
  has_many :appointments
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, :through => :appointments
  belongs_to :insurance
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :patients, :through => :appointments

  end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :appointments
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  has_many :appointments
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def report
      @appointments = Appointment.all
  end
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :set_time_slot, only: [:show, :edit, :update, :destroy]

  # GET /time_slots
  # GET /time_slots.json
  def index
    @time_slots = TimeSlot.all
  end

  # GET /time_slots/1
  # GET /time_slots/1.json
  def show
  end

  # GET /time_slots/new
  def new
    @time_slot = TimeSlot.new
  end

  # GET /time_slots/1/edit
  def edit
  end

  # POST /time_slots
  # POST /time_slots.json
  def create
    @time_slot = TimeSlot.new(time_slot_params)

    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully created.' }
        format.json { render :show, status: :created, location: @time_slot }
      else
        format.html { render :new }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slots/1
  # PATCH/PUT /time_slots/1.json
  def update
    respond_to do |format|
      if @time_slot.update(time_slot_params)
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_slot }
      else
        format.html { render :edit }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1
  # DELETE /time_slots/1.json
  def destroy
    @time_slot.destroy
    respond_to do |format|
      format.html { redirect_to time_slots_url, notice: 'Time slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_slot_params
      params.require(:time_slot).permit(:start_at, :end_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/office_days_helper.rb
module OfficeDaysHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/time_slots/_form.html.erb
<%= form_for @time_slot, :html => { :class => "form-horizontal time_slot" } do |f| %>

    <% if @time_slot.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @time_slot.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :start_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :start_at, :class => 'form-control' %>
    </div>
    <%= error_span(@time_slot[:start_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :end_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :end_at, :class => 'form-control' %>
    </div>
    <%= error_span(@time_slot[:end_at]) %>
  </div>

     <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            time_slots_path, :class => 'btn btn-default' %>

<% end %>

app/views/time_slots/edit.html.erb
<%- model_class = TimeSlot -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/time_slots/index.html.erb
<%- model_class = TimeSlot -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:start_at) %></th>
      <th><%= model_class.human_attribute_name(:end_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @time_slots.each do |time_slot| %>
      <tr>
        <td><%= link_to time_slot.id, time_slot_path(time_slot) %></td>
        <td><%= time_slot.start_at %></td>
        <td><%= time_slot.end_at %></td>
        <td><%= time_slot.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_time_slot_path(time_slot), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      time_slot_path(time_slot),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_time_slot_path,
            :class => 'btn btn-primary' %>

app/views/time_slots/new.html.erb
<%- model_class = TimeSlot -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/time_slots/show.html.erb
<%- model_class = TimeSlot -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:start_at) %>:</strong></dt>
  <dd><%= @time_slot.start_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_at) %>:</strong></dt>
  <dd><%= @time_slot.end_at %></dd>
  </dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              time_slots_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_time_slot_path(@time_slot), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              time_slot_path(@time_slot),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>